[tool.poetry]
name = "sparsekit"
version = "0.1.0"
description = "Sparsity Kit for Structured Sparsity Specification"
authors = ["Ayoub G. <research@ayghri.me>"]
readme = "README.md"
packages = [{include = "sparsekit"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
torch = ">=2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
